import React, { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, X, Info, CircleNotch, CaretDown, ArrowRight, BookmarkSimple, Check, FileText, GlobeHemisphereWest, Plug, WarningCircle, MagnifyingGlass } from '@phosphor-icons/react';
import { safeLink, host, readableDate } from './api.mjs';
import { EmptyArt } from './Artwork.jsx';
import { AiExplanation } from './AiControls.jsx';

export function ExternalLink({ href, children, className = '' }) {
  const safe = safeLink(href);
  return safe ? <a className={`external ${className}`} href={safe} target="_blank" rel="noopener noreferrer">{children}<ArrowUpRight size={15} aria-hidden="true" /></a> : null;
}
export function Notice({ children, error = false }) { return <div className={`notice ${error ? 'error' : ''}`} role={error ? 'alert' : undefined}>{error ? <WarningCircle size={19} aria-hidden="true" /> : <Info size={18} aria-hidden="true" />}<div>{children}</div></div>; }
export function Loading({ text = 'Reading public documentation…' }) { return <div className="loading" role="status"><CircleNotch className="spinner" size={21} aria-hidden="true" /><span>{text}</span></div>; }
export function Dialog({ title, onClose, children, wide = false }) {
  const ref = useRef(null);
  useEffect(() => { const dialog = ref.current; const previous = document.activeElement; dialog.showModal(); return () => { dialog.close(); if (previous?.isConnected) previous.focus(); }; }, []);
  return <dialog ref={ref} className={`dialog ${wide ? 'wide' : ''}`} aria-labelledby="dialog-title" onCancel={onClose} onClick={e => { if (e.target === ref.current) { const r = ref.current.getBoundingClientRect(); if (e.clientX < r.left || e.clientX > r.right || e.clientY < r.top || e.clientY > r.bottom) onClose(); } }}><div className="dialog-heading"><h2 id="dialog-title">{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X size={22} /></button></div><div className="dialog-body">{children}</div></dialog>;
}
export function Avatar({ item }) { return <div className={`avatar ${item.kind === 'mcp' ? 'mcp' : ''}`} aria-hidden="true">{item.kind === 'mcp' ? <Plug size={24} /> : (item.name?.match(/[A-Za-z0-9]/)?.[0] || 'A').toUpperCase()}</div>; }
export function ResultRow({ item, selected, saved, onSelect, onSave }) {
  return <article className={`result-row ${selected ? 'selected' : ''}`}><button className="result-open" aria-pressed={selected} onClick={e => onSelect(item, e.currentTarget)}><Avatar item={item} /><div className="result-copy"><div className="result-name"><h3>{item.name}</h3><ArrowRight size={18} className="result-arrow" aria-hidden="true" /></div><span className="provider">{item.provider} <span>· {item.kind === 'mcp' ? 'MCP server' : 'API'} · {item.version || 'Version unspecified'}</span></span><p>{item.description || 'This source does not include a description. Open the documentation to investigate.'}</p><div className="result-tags"><span><FileText size={13} />{item.specificationUrl ? 'Specification available' : 'Directory metadata'}</span>{item.matchedTerms?.slice(0, 3).map(term => <span className="match-term" key={term}>{term}</span>)}</div></div></button><button className={`save-button icon-button ${saved ? 'is-saved' : ''}`} aria-label={`${saved ? 'Remove' : 'Save'} ${item.name}${saved ? ' from' : ' to'} shortlist`} aria-pressed={saved} onClick={() => onSave(item)}>{saved ? <BookmarkSimple weight="fill" size={20} /> : <BookmarkSimple size={20} />}</button></article>;
}

function Capability({ cap, source }) {
  const fields = cap.responses.flatMap(r => r.fields).filter((f, i, all) => all.findIndex(other => other.name === f.name) === i);
  return <details className="capability"><summary><span className={`method ${cap.method.toLowerCase()}`}>{cap.method}</span><span>{cap.title}{cap.deprecated && <small>Marked deprecated</small>}</span><CaretDown size={16} aria-hidden="true" /></summary><div className="capability-content"><code className="endpoint">{cap.path}</code>{cap.description && <p>{cap.description}</p>}<h5>What you provide</h5>{cap.inputs.length ? <ul className="field-list">{cap.inputs.map((input, i) => <li key={`${input.location}-${input.name}-${i}`}><code>{input.name}</code><span>{input.required ? 'Required' : 'Optional'} · {input.description || input.location}</span></li>)}</ul> : <p className="muted">No parameters listed in this operation.</p>}{cap.requestBody && <p className="muted">{cap.requestBody.required ? 'A request body is required.' : 'An optional request body is documented.'} {cap.requestBody.fields.map(f => f.name).join(', ')}</p>}<h5>What comes back</h5>{fields.length ? <ul className="field-list">{fields.map(f => <li key={f.name}><code>{f.name}</code><span>{f.description || f.type}</span></li>)}</ul> : <p className="muted">{cap.responses.map(r => r.description).filter(Boolean).join(' ') || 'Output fields are not described in this summary.'}</p>}<h5>Access, as documented</h5><p className="muted">{cap.authentication.status === 'required-in-spec' ? 'Authentication is required in the specification. Your account permissions have not been checked.' : cap.authentication.status === 'no-auth-option-documented' ? 'A no-authentication option is documented. Availability and account access are still untested.' : 'Authentication is not declared here. Do not assume that means public access.'}</p><ExternalLink href={source.url}>Check source documentation</ExternalLink></div></details>;
}

export function Reader({ item, analysis, loading, error, onRead, onClose, onSave, saved, headingRef }) {
  const [filter, setFilter] = useState('');
  useEffect(() => setFilter(''), [item?.id, analysis?.id]);
  if (!item) return <aside className="reader reader-empty"><EmptyArt /><p className="eyebrow">A CLOSER LOOK</p><h2>Find something promising?</h2><p>Open a result to explore its documentation and see what still needs checking.</p><div className="reader-example"><FileText size={17} /> Documented capabilities <span>→</span></div><div className="reader-example"><BookmarkSimple size={17} /> Your next shortlist <span>→</span></div></aside>;
  const capabilities = analysis?.capabilities.filter(c => `${c.title} ${c.description} ${c.path}`.toLowerCase().includes(filter.toLowerCase())) || [];
  return <aside className="reader" aria-labelledby="reader-title"><div className="reader-topline"><span className="eyebrow">{analysis ? 'CAPABILITY READER' : 'A CLOSER LOOK'}</span><button className="icon-button" aria-label="Close API details" onClick={onClose}><X size={19} /></button></div><div className="reader-identity"><Avatar item={item} /><span>{item.kind === 'mcp' ? 'MCP SERVER' : 'API'}<small>{item.provider || host(item.specificationUrl || item.documentationUrl)}</small></span></div><h2 id="reader-title" ref={headingRef} tabIndex={-1}>{analysis?.title || item.name}</h2><p className="reader-description">{analysis?.purpose || item.description || 'Read the public documentation to explore this integration.'}</p><div className="reader-actions"><button className={`button secondary ${saved ? 'saved' : ''}`} onClick={() => onSave(item)}>{saved ? <Check size={17} /> : <BookmarkSimple size={17} />}{saved ? 'Shortlisted' : 'Shortlist'}</button><ExternalLink href={item.documentationUrl || item.specificationUrl}>Visit source</ExternalLink></div>
    {!analysis && !loading && <><div className="reader-divider"/><p className="eyebrow">BEYOND THE DESCRIPTION</p><h3>See what’s inside.</h3><p className="muted">{item.kind === 'mcp' ? 'A registry listing describes the server, not all its tools. Read its public docs without installing or running anything.' : 'Turn a public specification into a browsable view of capabilities, required inputs and returned data.'}</p>{item.specificationUrl || item.documentationUrl ? <button className="button primary full" onClick={() => onRead(item)}>Read documentation <ArrowRight size={17} /></button> : <Notice>This listing has no usable public documentation link. Try “Understand an API” with a public URL.</Notice>}<p className="fineprint">Directory descriptions are not verified capability claims.</p></>}
    {loading && <Loading />}{error && <Notice error>{error}<button className="text-button" onClick={() => onRead(item)}>Try again</button></Notice>}
    {analysis && <><div className="source-stamp"><FileText size={16} /><span>Read from documentation<small>{readableDate(analysis.source.fetchedAt)} · Not live-tested</small></span></div><Notice>{analysis.format === 'html' ? 'This is a readable page excerpt. Any AI explanation below is labelled separately.' : 'These are specification descriptions, not AI explanations. Account access and project fit still need checking.'}</Notice>
      <AiExplanation value={analysis.aiExplanation} evidence={analysis.evidence}/>
      {analysis.format === 'html' ? <div className="document-excerpt"><h3>From the documentation</h3><p>{analysis.documentExcerpt}</p>{analysis.coverage.truncated && <span className="muted">Excerpt truncated.</span>}</div> : <><div className="capability-heading"><h3>Documented capabilities</h3><span>{analysis.capabilities.length} / {analysis.coverage.totalOperations}</span></div><label className="within-search"><MagnifyingGlass size={16} /><input aria-label="Filter capabilities in this page" value={filter} onChange={e => setFilter(e.target.value)} placeholder="Find a capability on this page" /></label>{capabilities.map(cap => <Capability key={cap.id} cap={cap} source={analysis.source} />)}{!capabilities.length && <p className="muted">No capabilities match on this page.</p>}<div className="capability-pagination">{analysis.coverage.offset > 0 && <button className="text-button" disabled={loading} onClick={() => onRead(item, Math.max(0, analysis.coverage.offset - 20))}>Previous 20</button>}{analysis.coverage.nextOffset !== null && <button className="text-button" disabled={loading} onClick={() => onRead(item, analysis.coverage.nextOffset)}>Next capabilities <ArrowRight size={15}/></button>}</div>{analysis.coverage.status === 'partial' && <p className="fineprint">Partial view: some operations or schema details are not expanded.</p>}</>}
      <details className="unknowns"><summary>What still needs checking <CaretDown size={16} /></summary><ul>{analysis.unknowns.map((u, i) => <li key={i}>{u}</li>)}</ul></details><ExternalLink href={analysis.source.url}>Read the original source</ExternalLink></>}
  </aside>;
}
